import Head from "next/head";
import Image from "next/image";
import NavigationBar from "../components/NavigationBar";
import CarouselTop from "../components/CarouselTop";
import About from "../components/About";
import OurServices from "../components/OurServices";
import ChooseUs from "../components/ChooseUs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ER EXPERT RECRUIMENT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="row text-start">
          <NavigationBar />
          <CarouselTop />
          <OurServices />
          <hr className="hr-tag" style={{ height: "2px" }} />
          <About />
          <hr className="hr-tag" style={{ height: "2px", marginTop: "20px" }} />
          <ChooseUs />
        </div>
      </main>
    </div>
  );
}
