import Head from "next/head";
import Image from "next/image";
import NavigationBar from "../components/NavigationBar";
import CarouselTop from "../components/CarouselTop";
import About from "../components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="row text-start">
          <NavigationBar />
          <CarouselTop />
          <About />
        </div>
      </main>
    </div>
  );
}
